#!/usr/bin/env groovy

/*
    This Jenkinsfile uses the PythonPipeline from the Jenkins shared library
    https://confluence.vito.be/spaces/EP/pages/94143001/Python+pipeline
*/

@Library('lib')_

pythonPipeline {
  package_name            = 'histogram_sample_package'
  python_version          = ['3.11']
  create_tag_job          = true
  build_container_image   = true
  artifactory_server      = 'sas'
  docker_registry_dev     = 'terrascope-docker-local-dev.repo.vito.be'
  docker_registry_prod    = 'terrascope-docker-local-prod.repo.vito.be'
  wheel_repo_dev          = 'team-rise-pypi-local-dev'
  wheel_repo              = 'team-rise-pypi-local-prod'
  enable_uv               = true
  enable_caching          = true
  package_dir             = 'package'
  run_tests               = false
}